server:
  port: 8088
  tomcat:
    max-connections:
    max-threads:
spring:
  application:
    name: account-service  datasource:
    url: jdbc:mysql://localhost:3306/account
    username: root
    data-password: root
    driver-class-name: com.mysql.jdbc.Driver

